import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import type { Location, OpenGymSession } from "@/lib/types";

interface OpenGymPdfOptions {
  sessions: OpenGymSession[];
  locations: Location[];
  getUpcomingDates: (session: OpenGymSession, weeksAhead?: number) => Date[];
}

function formatTime(t: string): string {
  const [h, m] = t.split(":").map(Number);
  const ampm = h >= 12 ? "PM" : "AM";
  const hr = h % 12 || 12;
  return `${hr}:${m.toString().padStart(2, "0")} ${ampm}`;
}

export function generateOpenGymPdf({
  sessions,
  locations,
  getUpcomingDates,
}: OpenGymPdfOptions): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const locationsMap = new Map(locations.map((l) => [l.id, l]));

  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Open Gym / Court Rental Schedule", pageWidth / 2, 40, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated ${format(new Date(), "MMMM d, yyyy")}`, pageWidth / 2, 58, {
    align: "center",
  });

  let currentY = 80;

  // Session summaries
  for (const session of sessions) {
    if (currentY > doc.internal.pageSize.getHeight() - 100) {
      doc.addPage();
      currentY = 40;
    }

    const loc = session.location_id ? locationsMap.get(session.location_id) : null;

    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text(session.title, 40, currentY);
    currentY += 16;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");

    const details: string[] = [];
    if (session.sport) details.push(session.sport);
    if (loc) {
      let locText = loc.name;
      if (session.court_numbers.length > 0) locText += ` (${session.court_numbers.join(", ")})`;
      details.push(locText);
    }
    details.push(`${formatTime(session.start_time)} – ${formatTime(session.end_time)}`);
    if (session.capacity) details.push(`Capacity: ${session.capacity}`);
    if (session.fee_amount_cents) {
      const fee = `$${(session.fee_amount_cents / 100).toFixed(2)}`;
      details.push(session.fee_description ? `${fee} — ${session.fee_description}` : fee);
    }

    doc.text(details.join("  ·  "), 40, currentY);
    currentY += 12;

    if (session.description) {
      doc.setFont("helvetica", "italic");
      doc.text(session.description, 40, currentY, {
        maxWidth: pageWidth - 80,
      });
      currentY += 14;
    }

    if (session.notes) {
      doc.setFont("helvetica", "italic");
      doc.text(`Note: ${session.notes}`, 40, currentY, { maxWidth: pageWidth - 80 });
      currentY += 14;
    }

    // Upcoming dates table
    const dates = getUpcomingDates(session, 12);
    if (dates.length > 0) {
      const tableData = dates.map((d) => [
        format(d, "EEE, MMM d"),
        `${formatTime(session.start_time)} – ${formatTime(session.end_time)}`,
        loc?.name || "",
      ]);

      autoTable(doc, {
        startY: currentY + 4,
        head: [["Date", "Time", "Location"]],
        body: tableData,
        theme: "grid",
        headStyles: {
          fontStyle: "bold",
          fontSize: 8,
          textColor: [0, 0, 0],
          fillColor: [230, 230, 230],
          cellPadding: 3,
        },
        bodyStyles: { fontSize: 8, cellPadding: 3 },
        margin: { left: 40, right: 40 },
        tableWidth: pageWidth - 80,
      });

      const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;
      currentY = finalY + 20;
    } else {
      currentY += 10;
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text(
    "Generated by LeagueNight",
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 20,
    { align: "center" }
  );

  return doc;
}
